spring:
  application:
    name: simple-todo
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/demo?autoReconnect=true
    username: root
    password: whduddlek123!
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update